name: Torchboard Integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.0]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/ci.txt

    - name: Lint all files with black
      run: |
        python -m black --check torchboard
        python -m black --check tests

    - name: Check imports with isort
      run: |
        python -m isort --check torchboard
        python -m isort --check tests

    - name: Run tests with coverage
      run: coverage run tests

    - name: check token
      run: echo ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

    - name: Verify Package can be installed
      run: |
        pip install .
        python -c "import torchboard"
        pip uninstall -y torchboard
